const ADMIN_PASSWORD="0944379685_vuok";
const KEY="demobank_users_v2",REQKEY="demobank_requests_v2",SESSION="demobank_current_v2";
let users=JSON.parse(localStorage.getItem(KEY)||"[]"),requests=JSON.parse(localStorage.getItem(REQKEY)||"[]"),currentPhone=localStorage.getItem(SESSION),adminLogged=false,aiReady=false;
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat("vi-VN").format(Math.round(Number(n)||0))+"đ",now=()=>new Date().toLocaleString("vi-VN");
const save=()=>{localStorage.setItem(KEY,JSON.stringify(users));localStorage.setItem(REQKEY,JSON.stringify(requests))};
const uid=p=>p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8).toUpperCase(),user=()=>users.find(u=>u.phone===currentPhone);
const escapeHtml=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(msg){$("toast").textContent=msg;$("toast").className="show";setTimeout(()=>$("toast").className="",2800)}
function addNotice(u,title,text){u.notifications=u.notifications||[];u.notifications.unshift({id:uid("NT"),title,text,time:now(),read:false})}
function addTx(u,tx){u.transactions=u.transactions||[];u.transactions.unshift(tx)}
function render(){const u=user();if(!u){$("authView").classList.remove("hidden");$("appView").classList.add("hidden");$("logoutBtn").classList.add("hidden");return}$("authView").classList.add("hidden");$("appView").classList.remove("hidden");$("logoutBtn").classList.remove("hidden");let tx=u.transactions||[];$("welcome").textContent=u.email;$("balance").textContent=money(u.balance);$("accountPhone").textContent=u.phone;$("accountEmail").textContent=u.email;$("accountCreated").textContent=u.created;$("accountBalance").textContent=money(u.balance);$("receivedTotal").textContent=money(tx.filter(x=>x.type==="received").reduce((s,x)=>s+x.amount,0));$("sentTotal").textContent=money(tx.filter(x=>x.type==="sent").reduce((s,x)=>s+x.amount,0));$("txCount").textContent=tx.length;renderTransactions("recentTransactions",tx.slice(0,5));renderTransactions("historyList",filterHistory(tx));renderRequests();renderNotifications();renderAdmin();initAI()}
function filterHistory(tx){let f=$("historyFilter").value;return f==="all"?tx:tx.filter(x=>x.type===f)}
function renderTransactions(id,txs){let el=$(id);if(!txs.length){el.innerHTML='<div class="empty">Chưa có giao dịch.</div>';return}el.innerHTML=txs.map(t=>`<div class="tx"><div><b>${t.type==="received"?"↙ Tiền nhận":t.type==="sent"?"↗ Tiền chuyển":"＋ Tiền nạp"}</b><small>${escapeHtml(t.counterparty||"")} ${t.note?"• "+escapeHtml(t.note):""}<br>${t.time} • ${t.id}</small></div><strong class="${t.type==="received"||t.type==="deposit"?"positive":"negative"}">${t.type==="received"||t.type==="deposit"?"+":"-"}${money(t.amount)}</strong></div>`).join("")}
function renderRequests(){let mine=requests.filter(r=>r.phone===currentPhone);$("requestList").innerHTML=mine.length?mine.map(r=>`<div class="request"><div><b>${money(r.amount)}</b> <span class="badge ${r.status}">${r.status==="pending"?"Đang chờ duyệt":r.status==="approved"?"Đã duyệt":"Đã từ chối"}</span><small>${r.time} • ${r.id}</small></div></div>`).join(""):'<div class="empty">Chưa có yêu cầu.</div>'}
function renderNotifications(){let ns=user().notifications||[];$("notificationList").innerHTML=ns.length?ns.map(n=>`<div class="notice ${n.read?"":"unread"}"><div><b>${escapeHtml(n.title)}</b><div>${escapeHtml(n.text)}</div><small>${n.time}</small></div></div>`).join(""):'<div class="empty">Chưa có thông báo.</div>'}
function renderAdmin(){$("adminUsers").textContent=users.length;$("adminBalance").textContent=money(users.reduce((s,u)=>s+u.balance,0));$("adminPending").textContent=requests.filter(r=>r.status==="pending").length;if(!adminLogged)return;$("adminLogin").classList.add("hidden");$("adminPanel").classList.remove("hidden");let pending=requests.filter(r=>r.status==="pending");$("adminRequests").innerHTML=pending.length?pending.map(r=>`<div class="request"><div><b>${money(r.amount)}</b> • ${escapeHtml(r.phone)}<small>${escapeHtml(r.email)} • ${r.time} • ${r.id}</small></div><div class="admin-actions"><button class="btn primary" onclick="approveReq('${r.id}')">Duyệt</button><button class="btn danger" onclick="rejectReq('${r.id}')">Từ chối</button></div></div>`).join(""):'<div class="empty">Không có yêu cầu đang chờ.</div>';$('adminUsersList').innerHTML=users.map(u=>`<div class="user-row"><div><b>${escapeHtml(u.phone)}</b><small>${escapeHtml(u.email)} • Số dư: ${money(u.balance)}</small></div></div>`).join("")}
function showTab(id){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$(id).classList.remove("hidden");document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));render()}

// AI cục bộ: phân tích câu hỏi bằng nhiều tín hiệu (từ khóa, ngữ cảnh, số tiền, trạng thái yêu cầu, lịch sử) thay vì chỉ khớp vài câu cố định.
function normalize(s){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d")}
function scoreIntent(text,patterns){let score=0;patterns.forEach(p=>{if(p.test(text))score++});return score}
function aiData(u){let tx=u.transactions||[],pending=requests.filter(r=>r.phone===u.phone&&r.status==="pending"),approved=requests.filter(r=>r.phone===u.phone&&r.status==="approved"),received=tx.filter(x=>x.type==="received"),sent=tx.filter(x=>x.type==="sent"),deposits=tx.filter(x=>x.type==="deposit");return {tx,pending,approved,received,sent,deposits}}
function aiReply(question){const u=user();if(!u)return "Bạn cần đăng nhập để mình xem thông tin tài khoản demo.";const q=normalize(question.trim()),d=aiData(u);if(!q)return "Bạn hãy nhập câu hỏi nhé.";
  if(scoreIntent(q,[/xin chao|hello|hi|chao ban|alo/]))return `Xin chào 👋 Mình là DemoBank AI. Bạn cứ hỏi tự nhiên về tài khoản, số dư, chuyển khoản, nạp tiền, lịch sử, thông báo hoặc cách dùng website.`;
  if(scoreIntent(q,[/so du|con bao nhieu|bao nhieu tien|tien con|vi cua toi/]))return `Mình đã kiểm tra tài khoản demo của bạn. Số dư hiện tại là ${money(u.balance)}. Bạn có thể xem lại ở tab Tổng quan.`;
  if(scoreIntent(q,[/chuyen khoan|chuyen tien|gui tien|gui cho|tra tien|send/])){if(/khong du|thieu tien|khong chuyen|loi/.test(q))return `Nếu không chuyển được, bạn hãy kiểm tra 3 điều: người nhận đã đăng ký DemoBank, số tiền lớn hơn 0 và số dư của bạn đủ tiền. Số dư hiện tại: ${money(u.balance)}.`;return `Bạn muốn chuyển tiền thì vào tab Chuyển khoản → nhập số điện thoại 10 chữ số của người nhận → nhập số tiền → thêm nội dung nếu muốn → bấm “Xác nhận chuyển”. Người nhận phải có tài khoản DemoBank. Đây chỉ là giao dịch demo.`}
  if(scoreIntent(q,[/nap tien|nap|bo sung tien|them tien|deposit/])){if(d.pending.length)return `Bạn đang có ${d.pending.length} yêu cầu nạp tiền chưa được duyệt. Vì vậy số dư chưa tăng. Hãy vào tab Yêu cầu để xem chi tiết.`;if(/chua|chua thay|khong vao|khong cong|chua duoc cong|cho/.test(q))return `Nếu vừa nạp mà chưa thấy tiền, hãy mở tab Yêu cầu. Yêu cầu phải ở trạng thái “Đã duyệt” thì số dư demo mới được cộng.`;return `Để nạp tiền demo: mở tab Nạp tiền → nhập số tiền → gửi yêu cầu. Sau đó Admin phải duyệt thì số dư mới được cộng.`}
  if(scoreIntent(q,[/lich su|giao dich|da nhan|da chuyen|chi tieu|transaction/])){if(!d.tx.length)return `Hiện tài khoản của bạn chưa có giao dịch nào.`;let totalIn=d.received.reduce((s,x)=>s+x.amount,0),totalOut=d.sent.reduce((s,x)=>s+x.amount,0);return `Mình đã xem lịch sử demo của bạn:\n• ${d.tx.length} giao dịch\n• Tiền nhận: ${money(totalIn)}\n• Tiền chuyển: ${money(totalOut)}\n• Tiền nạp: ${money(d.deposits.reduce((s,x)=>s+x.amount,0))}\n\nBạn có thể mở tab Lịch sử để xem từng giao dịch.`}
  if(scoreIntent(q,[/yeu cau|cho duyet|pending|admin duyet|duyet/])){if(!d.pending.length)return `Hiện bạn không có yêu cầu nạp tiền nào đang chờ duyệt.`;return `Bạn đang có ${d.pending.length} yêu cầu nạp tiền chờ Admin duyệt, tổng ${money(d.pending.reduce((s,r)=>s+r.amount,0))}. Mở tab Yêu cầu để xem mã và trạng thái.`}
  if(scoreIntent(q,[/tai khoan|thong tin ca nhan|so dien thoai|email|dang ky/]))return `Thông tin tài khoản demo:\n• Số điện thoại: ${u.phone}\n• Email: ${u.email}\n• Ngày đăng ký: ${u.created}\n• Số dư: ${money(u.balance)}\n\nBạn có thể xem tại tab Tài khoản.`;
  if(scoreIntent(q,[/thong bao|notification|tin nhan/])){let unread=(u.notifications||[]).filter(n=>!n.read).length;return unread?`Bạn đang có ${unread} thông báo chưa đọc. Mở tab Thông báo để xem.`:`Hiện bạn không có thông báo chưa đọc.`}
  if(scoreIntent(q,[/admin|quan tri|mat khau/]))return `Tab Admin là khu vực quản trị của website demo, dùng để xem tài khoản và duyệt yêu cầu nạp tiền. Không nên đưa mật khẩu Admin vào hệ thống thật vì bản demo lưu logic ở phía trình duyệt.`;
  if(scoreIntent(q,[/bao nhieu giao dich|may giao dich|tong giao dich/]))return `Tài khoản của bạn hiện có ${d.tx.length} giao dịch.`;
  if(scoreIntent(q,[/website|su dung|lam gi|co nhung gi|tinh nang|huong dan/]))return `DemoBank hiện có các khu vực: Tổng quan, Chuyển khoản, Nạp tiền, Lịch sử, Yêu cầu, Thông báo, AI hỗ trợ, Tài khoản và Admin. Bạn có thể hỏi mình về bất kỳ khu vực nào.`;
  return `Mình chưa chắc bạn đang hỏi phần nào, nhưng mình có thể hiểu các câu hỏi tự nhiên về:\n• 💰 Số dư và tiền hiện có\n• 💸 Chuyển khoản cho người khác\n• ＋ Nạp tiền và trạng thái duyệt\n• 📜 Lịch sử nhận/chuyển/nạp\n• 🔔 Thông báo\n• 👤 Thông tin tài khoản\n• 🧭 Cách sử dụng website\n\nBạn hãy hỏi cụ thể hơn một chút, ví dụ: “Tại sao tiền nạp của tôi chưa được cộng?”`;
}
function addAI(text,who="ai"){let box=$("aiMessages");if(!box)return;let div=document.createElement("div");div.className="ai-msg "+who;div.textContent=text;box.appendChild(div);box.scrollTop=box.scrollHeight}
function initAI(){if(aiReady)return;aiReady=true;document.querySelectorAll("[data-ai]").forEach(b=>b.onclick=()=>{let q=b.dataset.ai;addAI(q,"user");setTimeout(()=>addAI(aiReply(q)),250)});$("aiForm").onsubmit=e=>{e.preventDefault();let q=$("aiText").value.trim();if(!q)return;addAI(q,"user");$("aiText").value="";setTimeout(()=>addAI(aiReply(q)),250)};addAI("Xin chào 👋 Mình là DemoBank AI. Bạn cứ hỏi bằng câu của bạn, mình sẽ phân tích câu hỏi và dựa vào dữ liệu demo hiện tại để trả lời.")}

document.querySelectorAll(".switch-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".switch-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("loginForm").classList.toggle("hidden",b.dataset.auth!=="login");$("registerForm").classList.toggle("hidden",b.dataset.auth!=="register")});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>showTab(b.dataset.go));
$("loginForm").onsubmit=e=>{e.preventDefault();let id=$("loginIdentity").value.trim().toLowerCase(),pw=$("loginPassword").value,u=users.find(x=>(x.email.toLowerCase()===id||x.phone===id)&&x.password===pw);if(!u)return toast("Sai thông tin đăng nhập.");currentPhone=u.phone;localStorage.setItem(SESSION,currentPhone);toast("Đăng nhập thành công.");render()};
$("registerForm").onsubmit=e=>{e.preventDefault();let phone=$("regPhone").value.trim(),email=$("regEmail").value.trim().toLowerCase(),password=$("regPassword").value;if(!/^\d{10}$/.test(phone))return toast("Số điện thoại phải đúng 10 chữ số.");if(users.some(u=>u.phone===phone))return toast("Số điện thoại đã tồn tại.");if(users.some(u=>u.email.toLowerCase()===email))return toast("Email đã tồn tại.");users.push({phone,email,password,balance:0,created:now(),transactions:[],notifications:[]});save();currentPhone=phone;localStorage.setItem(SESSION,phone);toast("Tạo tài khoản thành công.");render()};
$("logoutBtn").onclick=()=>{localStorage.removeItem(SESSION);currentPhone=null;adminLogged=false;render();toast("Đã đăng xuất.")};
$("transferForm").onsubmit=e=>{e.preventDefault();let u=user(),phone=$("transferPhone").value.trim(),amount=Number($("transferAmount").value),note=$("transferNote").value.trim(),receiver=users.find(x=>x.phone===phone);if(!/^\d{10}$/.test(phone))return toast("Số điện thoại phải đúng 10 chữ số.");if(phone===u.phone)return toast("Không thể chuyển tiền cho chính mình.");if(!receiver)return toast("Không tìm thấy người nhận.");if(!Number.isFinite(amount)||amount<=0)return toast("Số tiền không hợp lệ.");if(u.balance<amount)return toast("Số dư không đủ.");let id=uid("TX"),time=now();u.balance-=amount;receiver.balance+=amount;addTx(u,{id,time,type:"sent",amount,counterparty:`Đến ${receiver.phone}`,note});addTx(receiver,{id,time,type:"received",amount,counterparty:`Từ ${u.phone}`,note});addNotice(receiver,"Bạn vừa nhận tiền",`${money(amount)} từ ${u.phone}${note?" • "+note:""}`);save();e.target.reset();toast("Chuyển tiền thành công.");render()};
$("depositForm").onsubmit=e=>{e.preventDefault();let amount=Number($("depositAmount").value);if(!Number.isFinite(amount)||amount<=0)return toast("Số tiền không hợp lệ.");let r={id:uid("REQ"),phone:currentPhone,email:user().email,amount,time:now(),status:"pending"};requests.unshift(r);addNotice(user(),"Đã gửi yêu cầu nạp tiền",`Yêu cầu ${r.id} trị giá ${money(amount)} đang chờ Admin duyệt.`);save();e.target.reset();toast("Đã gửi yêu cầu nạp tiền.");render()};
$("historyFilter").onchange=render;$("readAllBtn").onclick=()=>{(user().notifications||[]).forEach(n=>n.read=true);save();render()};$("adminForm").onsubmit=e=>{e.preventDefault();if($("adminPassword").value!==ADMIN_PASSWORD)return toast("Mật khẩu Admin không đúng.");adminLogged=true;$("adminPassword").value="";renderAdmin();toast("Đăng nhập Admin thành công.")};$("adminLogout").onclick=()=>{adminLogged=false;$("adminLogin").classList.remove("hidden");$("adminPanel").classList.add("hidden");toast("Đã thoát Admin.")};
window.approveReq=id=>{let r=requests.find(x=>x.id===id);if(!r||r.status!=="pending")return;let u=users.find(x=>x.phone===r.phone);if(!u)return toast("Không tìm thấy tài khoản.");r.status="approved";u.balance+=r.amount;addTx(u,{id:uid("TX"),time:now(),type:"deposit",amount:r.amount,counterparty:"Nạp tiền qua Admin",note:`Yêu cầu ${r.id}`});addNotice(u,"Yêu cầu nạp tiền được duyệt",`Bạn đã được cộng ${money(r.amount)} vào số dư.`);save();toast("Đã duyệt yêu cầu.");render()};
window.rejectReq=id=>{let r=requests.find(x=>x.id===id);if(!r||r.status!=="pending")return;let u=users.find(x=>x.phone===r.phone);r.status="rejected";if(u)addNotice(u,"Yêu cầu nạp tiền bị từ chối",`Yêu cầu ${r.id} trị giá ${money(r.amount)} đã bị từ chối.`);save();toast("Đã từ chối yêu cầu.");render()};
render();
